In [1]:
import numpy as np
import math

In [23]:
cc=np.loadtxt("region_distance.csv")

In [43]:
# 建立边的数组
def create_A_L(inputFileName):
    f = open(inputFileName, 'r')
    lines = f.readlines()
    f.close()
    Adj_mat = []
    for line in lines[0:]:
        l = line.strip('\n\r').split(' ')
        Adj_mat.append(l[0:])
    Adj_mat = np.array(Adj_mat, dtype=np.float32)
    for i in range(157):
        for j in range(i-1,157):
            if i == j:
                Adj_mat[i][j] = 0
            else :
                Adj_mat[i][j] = Adj_mat[i][j]+Adj_mat[j][i]
                Adj_mat[j][i] = Adj_mat[i][j]
    return Adj_mat
c=create_A_L("flow.txt")

In [27]:
ccc=cc

In [44]:
for i in range(157):
    for j in range(i-1,157):
        if cc[i][j] > 300:
            a = 0
        else:
            a = (300 - cc[i][j])/300
        if c[i][j] > 50:
            b = 1
        else:
            b=c[i][j]/50
        ccc[i][j]=(a+b)/2
        ccc[j][i]=ccc[i][j]
        if(i==j):
            ccc[i][j]=1

In [45]:
ccc.max()

1.0

In [46]:
for i in range(157):
    for j in range(i-1,157):
        if ccc[i][j] < 0:
            ccc[i][j] = 0
            ccc[j][i] = 0
print(ccc)

[[1.         0.49916805 0.49916667 ... 0.50915004 0.56905029 0.55906822]
 [0.49916805 1.         0.49916805 ... 0.49916667 0.49916667 0.49916667]
 [0.49916667 0.49916805 1.         ... 0.49916667 0.49916667 0.49916667]
 ...
 [0.50915004 0.49916667 0.49916667 ... 1.         0.57903494 0.49916667]
 [0.56905029 0.49916667 0.49916667 ... 0.57903494 1.         0.49916805]
 [0.55906822 0.49916667 0.49916667 ... 0.49916667 0.49916805 1.        ]]


In [47]:
ccc.sum(axis=0)

array([91.40912168, 78.8999529 , 78.87998615, 78.87998615, 78.90993627,
       78.93988637, 79.22940425, 79.60877252, 78.87000277, 78.88996952,
       78.87000277, 79.4190884 , 78.87000277, 78.87000277, 79.1395539 ,
       78.88996952, 78.87000277, 81.10627877, 78.87000277, 78.9398864 ,
       78.94986977, 80.18780827, 78.88996952, 79.31925465, 78.87000277,
       79.00977002, 78.9798199 , 78.87998615, 78.87000277, 78.98980327,
       78.9798199 , 78.87000277, 81.83506515, 78.88996952, 80.26767527,
       78.91991965, 78.92990302, 78.94986977, 78.91991965, 79.1395539 ,
       79.03972015, 78.87000277, 78.87000277, 79.2194209 , 78.95985315,
       79.98814077, 78.87000277, 79.67865615, 79.54887227, 78.9798199 ,
       78.91991965, 78.8999529 , 78.87998615, 79.23938762, 79.07965359,
       81.02641172, 78.91991962, 78.90993627, 79.2194209 , 81.6553644 ,
       78.87000277, 78.90993627, 83.4124384 , 78.8999529 , 78.87000277,
       78.95985315, 78.91991965, 79.44903852, 78.87000277, 80.30

In [48]:
np.savetxt('output.txt', ccc)

In [ ]:
# 代码行43